//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmTable
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public string trailer { get; set; }
        public Nullable<System.DateTime> year { get; set; }
    }
}
